apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fullstack
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80          # << Der Port, den andere nutzen
      targetPort: 3000  # << Der Port, auf dem dein Container wirklich hört!